FROM ghcr.io/graalvm/native-image-community:17 as build
RUN mkdir /opt/src
RUN microdnf install findutils

COPY ./ /opt/src

RUN chmod +x /opt/src/gradlew && \
    /opt/src/gradlew --version

RUN cd /opt/src && \
    chmod +x gradlew && \
    ./gradlew nativeCompile

FROM docker.io/library/ubuntu
COPY --from=build /opt/src/build/native/nativeCompile/alldicesbot /opt/app
CMD /opt/app