FROM ghcr.io/graalvm/native-image-community:17 as build
RUN mkdir /opt/app /opt/build
COPY build/install/alldicesbot/lib/* /opt/app
RUN native-image -cp "/opt/app/*" --static --no-fallback ru.ramlabs.alldicesbot.Main /opt/build/app

FROM docker.io/library/alpine
COPY --from=build /opt/build/app /opt
CMD /opt/app
