name: Build and publish native container
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Fix permissions
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew test
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install app
        run: ./gradlew installDist
      - name: Install QEMU
        run: sudo apt-get install qemu-user-static -y
      - name: Create manifest
        run: buildah manifest create app:latest-native
      - name: Build amd64
        run: buildah build --manifest app:latest-native --arch amd64 -f Containerfile.native
      - name: Build arm64
        run: buildah build --manifest app:latest-native --arch arm64 -f Containerfile.native
      - name: Log in to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
      - name: Push container
        run: buildah manifest push --all app:latest-native docker://ghcr.io/ram042/everydicebot:latest-native